/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b0c6ff",
        "surface-container-highest": "#353534",
        "on-tertiary-container": "#002f33",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#00429c",
        "on-surface-variant": "#c2c6d8",
        "on-tertiary": "#00363a",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-primary-fixed": "#001945",
        "secondary-fixed-dim": "#ecb2ff",
        "tertiary": "#00dbe9",
        "surface-tint": "#b0c6ff",
        "on-background": "#e5e2e1",
        "tertiary-container": "#00a0aa",
        "on-error-container": "#ffdad6",
        "primary-container": "#568dff",
        "on-tertiary-fixed": "#002022",
        "outline-variant": "#424655",
        "on-primary": "#002d6f",
        "secondary-container": "#cf5cff",
        "on-secondary": "#520071",
        "on-tertiary-fixed-variant": "#004f54",
        "background": "#131313",
        "outline": "#8c90a1",
        "primary": "#b0c6ff",
        "on-secondary-container": "#480063",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#74009f",
        "tertiary-fixed": "#7df4ff",
        "on-primary-container": "#002661",
        "on-secondary-fixed": "#320047",
        "on-surface": "#e5e2e1",
        "secondary": "#ecb2ff",
        "surface": "#131313",
        "tertiary-fixed-dim": "#00dbe9",
        "primary-fixed": "#d9e2ff",
        "surface-container": "#201f1f",
        "surface-dim": "#131313",
        "inverse-primary": "#0058cb",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "secondary-fixed": "#f8d8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "gutter": "16px",
        "container-padding": "24px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
